PROJETRETRO RESTRICTED LICENSE

Copyright 2021 ophelien.duparc@projetretro.io

THIS PROJECT AND ALL IT'S CONTENT IS PROTECTED UNDER THE COPYRIGHT LAW AND CANNOT BE COPIED, USED OR DISTRIBUTED WITHOUT THE EXPRESSED PERMISSION OF PROJETRETRO OR ITS SUPPLIERS.

This license file must be submitted with each copy of the project.